### ISSUE TITLE
Live demo returns a 500 Internal Server Error

### ISSUE THREAD

**Issue by rmacy** [hapijs/lout#100]
https://www.dropbox.com/s/fp22tgv8hsjpmi3/Screenshot%202015-01-05%2010.39.05.png?dl=0

**Comment by Marsup** [comment]
Already working on it for #99.

**Comment by Marsup** [comment]
And it's back !

**Comment by eiriksm** [comment]
Hey!

Not sure if this is temporary, but right now the demo is down again. Just FYI :)

By the way, thanks for making this and having it available.

**Comment by Marsup** [comment]
@eiriksm fixed. It breaks every now and then when hapi updates.
