### ISSUE TITLE
Serving 2 instances of lout

### ISSUE THREAD

**Issue by leesei** [hapijs/lout#101]
```js
var Hapi = require('hapi');
var server = new Hapi.Server();

server.connection({ port: 80 });

// v1 api
server.register(
  { register: require('./api-v1') },
  { routes: { prefix: '/api/v1' } },
  function(err) { }
);

// v2 api
server.register(
  { register: require('./api-v2') },
  { routes: { prefix: '/api/v2' } },
  function(err) { }
);

server.register({ register: require('lout') }, function(err) { });

server.start();
```

In this config, all v1 and v2 API are served at `http://localhost/docs`.
How to separate them into `http://localhost/api/v1/docs` and `http://localhost/api/v2/docs`?
Thanks.

**Comment by Marsup** [comment]
I think you'll have to register lout twice and use labels (http://hapijs.com/api#serverregisterplugins-options-callback - select part) on both to do that. It's never been tried, can you tell me if this works ?

**Comment by leesei** [comment]
I thought about that but I only have one connection (which serves both v1
and v2 API).

**Comment by Marsup** [comment]
Instead of introducing a new concept, I allowed multiple registration of the plugin, see the test case in that commit for an example.
