### ISSUE TITLE
CORS config renders as [object Object]

### ISSUE THREAD

**Issue by wraithgar** [hapijs/lout#102]
Looks like it's just calling toString() https://github.com/hapijs/lout/blob/master/lib/index.js#L196

**Comment by Marsup** [comment]
I'm currently busy with Joi, I'll see what can be done later if you don't mind, unless you want to start a PR.

**Comment by wraithgar** [comment]
I'd be happy to, with a little bit of direction. What is the intent of this supposed to be? A true/false display?  Or the whole object.  If it's the whole object then displaying it w/o overpowering the whole view seems non-trivial.

**Comment by Marsup** [comment]
I'll close this one to continue discussions in the PR.
