### ISSUE TITLE
Document route configurations that lout display

### ISSUE THREAD

**Issue by ssylvia** [hapijs/lout#105]
The live demos has many routes that include descriptions, examples, tags, request parameters, etc. Are these documented anywhere?

**Comment by Marsup** [comment]
I don't understand the question, what should be documented ? Hapi ?

**Comment by ssylvia** [comment]
How do you get the additional information under the main route? Is there documentation for what can be displayed?

![screen shot 2015-02-26 at 4 30 06 pm](https://cloud.githubusercontent.com/assets/1211360/6402347/e352349a-bdd4-11e4-9cb5-3a2b482192b4.png)

**Comment by Marsup** [comment]
In theory almost everything that hapi and joi can do should be covered, so refer to those documentation to know what's possible.

**Comment by Jamesford** [comment]
@ssylvia this might be what you were looking for http://hapijs.com/tutorials/routing#config

I think that link should be included somewhere in lout's readme.md, I was lost on how to add more detailed info until I found that.

**Comment by Marsup** [comment]
Feel free to make a PR about that.
