### ISSUE TITLE
Heroku demo not working

### ISSUE THREAD

**Issue by nelsonic** [hapijs/lout#106]
Hi!
tried to reach: http://lout.herokuapp.com/
but saw:
![screen shot 2015-03-15 at 15 20 49](https://cloud.githubusercontent.com/assets/194400/6656620/00316edc-cb27-11e4-8099-5345434631db.png)
Just thought you should know.

**Comment by Marsup** [comment]
Fixed.

**Comment by nelsonic** [comment]
:+1:
