### ISSUE TITLE
Joi .strip() information is not given to lout

### ISSUE THREAD

**Issue by franciscogouveia** [hapijs/lout#110]
I'm trying to hide stripped out attributes from response schemas, in the lout templates. Unfortunately, I can't find a way to do identify stripped out attributes.

Example of a response schema:

```
Joi.object({
  'thisShouldBeRemoved': Joi.any().strip(),
  'otherField': Joi.string()
})
```

Gives the following to lout:

```
{
    "type": "object",
    "allowedValues": null,
    "disallowedValues": null,
    "target": null,
    "children": [
        {
            "name": "thisShouldBeRemoved",
            "type": "any",
            "allowedValues": null,
            "disallowedValues": null,
            "target": null,
            "flags": {
                "allowUnknown": false,
                "required": false,
                "forbidden": false
            },
            "rules": {}
        },
        {
            "name": "otherField",
            "type": "string",
            "allowedValues": null,
            "disallowedValues": null,
            "target": null,
            "rules": {}
        }
    ],
    "rules": {}
}
```

What I would expect is, e.g. a flag with `stripped: true` on the child named `thisShouldBeRemoved`. Or am I missing something?

Thank you

----

Using:
* lout@6.2.2
* joi@6.5.0
* hapi@8.6.1

**Comment by Marsup** [comment]
IMHO it should be removed from lout, it's an implementation detail that the end-user will never see.

**Comment by Marsup** [comment]
Actually since the fields are validated before being stripped, I opted for a new icon next to the field. Hope it solves your problem.

**Comment by franciscogouveia** [comment]
Perfect, thanks!
