### ISSUE TITLE
Add `vision` as dependency / hapi@9 update

### ISSUE THREAD

**Issue by gr2m** [hapijs/lout#115]
After upgrading to [hapi@9](https://github.com/hapijs/hapi/issues/2682) I get this error

```
TypeError: Object [object Object] has no method 'views'
    at Object.exports.register (myapp/node_modules/lout/lib/index.js:53:10)
    at Items.serial.self.root._registring (myapp/node_modules/hapi/lib/plugin.js:255:14)
    at iterate (myapp/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (myapp/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at internals.Plugin.register (myapp/node_modules/hapi/lib/plugin.js:234:11)
    at myapp/index.js:135:12
```

The built-in plugin for views have been removed. So we need to add `vision` as dependency I guess?

**Comment by gr2m** [comment]
I'm trying to put together a PR for this

**Comment by gr2m** [comment]
Okay sorry I can't figure it out. I thought adding it as dependency and `dependencies` to `register.dependencies` would do the trick

```
exports.register.attributes = {
    pkg: require('../package.json'),
    multiple: true,
    dependencies: 'vision'
};
```

I'd love to learn how to add a dependency to a plugin :) Sorry I can't be of better help right now

**Comment by Marsup** [comment]
That was close. The dependencies attribute is a bit misleadind in that the dependencies are not loaded before, it's only guaranteed they'll be there when the server starts. So what you need to do is use `server.dependency` with a callback, basically surrounding the meaningful parts of the current register (only the server.* calls). Thanks for the helping hand !

**Comment by Marsup** [comment]
Btw you'll probably also need `inert` to serve files. Only add them as peer and dev dependencies.

**Comment by gr2m** [comment]
Thanks a lot @Marsup, I'll give this a go later today

**Comment by Marsup** [comment]
Sorry, I went ahead and did it. Next time ;)

**Comment by gr2m** [comment]
no worries :) thanks
