### ISSUE TITLE
Doesn't show authentication information when strategy is required by default

### ISSUE THREAD

**Issue by brabster** [hapijs/lout#119]
If I set up a strategy to be required by default, Lout doesn't show any auth strategy information for the routes (including if I then explicitly disable auth for a particular route)

Is this an oversight or by design?

**Comment by Marsup** [comment]
The auth information seem to show in the demo server, can you provide a failing test ?

**Comment by j** [comment]
I noticed this as well.

I simply was testing it with one route and having a default required authentication for all routes:

```javascript
server.auth.strategy('token', 'jwt', 'required', {
    key: Config.jwt.secret
});

server.route({
    description: 'Foo',
    response: {
        schema: Joi.object().keys({
            bar: Joi.string().required()
        })
    },
    handler: function (request, reply) {

        reply({ bar: "baz" });
    }
});
```

Then the docs don't say that that route requires authentication.

**Comment by Marsup** [comment]
Well `route.settings.auth === undefined`, not sure what to do here.
@hueniverse that's a hapi bug or should I check `route.connection.auth.settings.default` each time I don't find an auth ?

**Comment by hueniverse** [comment]
Use this: https://github.com/hapijs/hapi/blob/master/lib/auth.js#L164-L171

`connection.auth.lookup(route)` instead of writing your own code.
