### ISSUE TITLE
Registering lout

### ISSUE THREAD

**Issue by prashaantt** [hapijs/lout#122]
I'm a week old to Hapi. After half an hour of wracking my brains, I figured out how to register `lout` by changing the code thus:

```
server.register([require('vision'), require('inert'), { register: require('lout') }], function(err) {
});
```

instead of 

```
server.register(require('vision'), require('inert'), { register: require('lout') }, function(err) {
});
```

per the docs (in two places). Please let me know if I'm missing something.

**Comment by devinivy** [comment]
Yes, `server.register()` only takes two or three arguments (http://hapijs.com/api#serverregisterplugins-options-callback), so the docs do need to be updated to correct the typo.

**Comment by Marsup** [comment]
Oh sorry, I was a bit quick updating the docs :p
