### ISSUE TITLE
Documenting error behaviors

### ISSUE THREAD

**Issue by kpdecker** [hapijs/lout#128]
I have a request from my client guys to improve the documentation of our errors, i.e. a full enumeration of what expected cases may occur and the data that is associated with them.

Wondering if lout could be applied for this. It seems like there are two major concerns:

1. Global errors (i.e. validation, auth, etc)
2. Per-route errors

The later seems like it could follow a structure similar to `config.response.status` providing an enum of the HTTP status codes and then allowing each to drill down into a Joi schema. The former is not as clear to me on what options may be and perhaps this is easier to just describe using human language in a markdown doc.

**Comment by Marsup** [comment]
Hapi exposes route statuses so we should indeed use that, unfortunately I don't think there's any central description of errors that might happen in the request lifecycle. eg. There's no way for hapi to know in advance that a prerequisite will takeover the response with custom status codes.

Unless hapi changes that, I think we'll have to have a custom transformation step in describing the routes to add those elements depending on whether the route has auth or not, prerequisites or not, ... This is going to be tricky in some cases.

@hueniverse any input on what might be doable in hapi definitions ?

**Comment by hueniverse** [comment]
We could add error response validation where this stuff can live, but other than that, I am not sure. Keep in mind that auth scheme just meen 401 is possible, but the scheme can return anything. I think this might be more hassle than its worth.

**Comment by kpdecker** [comment]
For the global, I think it's fair that this is extremely hard to document since there are any number of plugins that could impact this. For now I'm manually constructing validation fields for that based on what my specific environment does. Potentially brittle, but when combined with log only response validation mode, shouldn't have much impact and has a better chance of being kept up to date over random markdown that is never validated against the system behaviors.

Likely can close this out as best effort once #136 is closed.
