### ISSUE TITLE
Properly display Joi ordered arrays

### ISSUE THREAD

**Issue by kpdecker** [hapijs/lout#130]
https://github.com/hapijs/joi/pull/688 lands support for ordered arrays in Joi. This needs to be supported by lout.

Some discussion on this occurred in #126

**Comment by kpdecker** [comment]
One idea is that the name field could be exposed here as the numeric value, similar to how objects work.

As a quick ASCII example:
```
[
  1: Integer
  2: Foo
     String
]
```

I'm not sure how clear this would be. It seems like it may be a bit too subtle if you aren't expected it.

**Comment by Marsup** [comment]
Same problem with forbidden values now that I think about it. What about :
```js
[
  1: Integer
  2: Foo
  One of :
     String
     Date
  None of :
     Boolean
]
```
