### ISSUE TITLE
How to display a version number for the API?

### ISSUE THREAD

**Issue by varmint09** [hapijs/lout#132]
Hi,

It would be great if in the lout configuration, there was a value for setting the API version, so that when viewing the docs, it can also easily confirm that the latest API version is deployed.

I understand there are approaches around namespacing an API, or sending the version in headers; but this request is for something purely cosmetic which would aid understanding, it doesn't need to be an auto-incrementing version or anything.

So then it would be something like "Route Documentation - v0.1.1" rather than just Route Documentation in the navbar.

Thoughts?

**Comment by Marsup** [comment]
Sorry for the delay. Feel free to submit a PR to support that through configuration.
