### ISSUE TITLE
Inline single constant values

### ISSUE THREAD

**Issue by kpdecker** [hapijs/lout#133]
```
    errorCode: Joi.string().equal(Account.USER_DOES_NOT_EXIST)
```

Renders as:
![image](https://cloud.githubusercontent.com/assets/196390/10699109/23e7ec0a-797a-11e5-9be2-6db7e4ddb838.png)

Ideally we simplify this to something like
```
  errorCode: 'user_does_not_exist'
```

Potentially may want to consider inlining all enum options, i.e.:

```
  errorCode: one of "user_does_not_exist"
```

Since the type display doesn't mean too much since we only allow a valid subset of what the full type is.

**Comment by Marsup** [comment]
Agreed, do you want to take it ?

**Comment by kpdecker** [comment]
I'm playing around so I can try to do a PR for this.
