### ISSUE TITLE
Restrict docs

### ISSUE THREAD

**Issue by furyscript** [hapijs/lout#142]
How can I restrict permissions to route documentation?

I'm thinking http based authentication with nginx proxy, but there is a way to enter in page with some password or similar?

**Comment by Marsup** [comment]
If you already have an nginx in front of your node yes, currently that's not built-in.

**Comment by furyscript** [comment]
Uhm ok thanks, is it possible that this feature can be added?? I think that can be only with username and password, without too much hard code :+1:

**Comment by Marsup** [comment]
If you want it it'll have to be a hapi compatible solution, I'm not going to implement a whole new auth solution just for that.

**Comment by furyscript** [comment]
ok, so what do you suggest ?

**Comment by Marsup** [comment]
Like I just said, we need to allow an extension point to provide your own auth.

**Comment by furyscript** [comment]
Ok, I hope this feature come in the future!

**Comment by furyscript** [comment]
Hi @Marsup, do you have some news about that? :smile:

**Comment by Marsup** [comment]
Actually I should have closed this since you can already provide an auth option, so same as any other hapi route.

**Comment by furyscript** [comment]
So by default, restrict docs won't be implemented? You could simply add two params on the route docs like /docs?username=admin&password=admin :smile: .

**Comment by Marsup** [comment]
Add this with your custom scheme, look at how auth is done on hapi, maybe basic-auth is enough for your use case, but no I won't be implementing any specific lout auth.
