### ISSUE TITLE
Option for manually setting server

### ISSUE THREAD

**Issue by ryanwalters** [hapijs/lout#147]
Is there an option for manually setting the server that lout uses as the `?server=` parameter?

For example, Heroku internally uses temporary urls like `http://cd0304e8-118a-4cde-a078-6f65545396ad:5253`. This works for the lifetime of that temporary url, but then the docs begin going to 404 if they keep using the old url as the `server` param.

It would be nice if there was an option like:

```
{
    server: 'api.mysite.com'
}
```

Also, this could be beneficial from a display perspective.
```
Routes for https://api.mysite.com
```
...looks better than...
```
Routes for http://cd0304e8-118a-4cde-a078-6f65545396ad:5253
```

**Comment by Marsup** [comment]
You should set the `uri` property on your connections, it'll use it.

**Comment by ryanwalters** [comment]
Perfect, thanks.
