### ISSUE TITLE
Dependencies update?

### ISSUE THREAD

**Issue by LasaleFamine** [hapijs/lout#160]
What about a little dependencies refresh? Can break something?

**Comment by Marsup** [comment]
Nothing critical to update, what are you thinking about ?

**Comment by LasaleFamine** [comment]
Hi @Marsup, thank you for your response.

Sorry but the badges on the README may appear equivocal.

I didn't check correctly that they are just "required" versions.
Anyway, I think maybe the `hapi` devDep could be upgraded to a major version (https://david-dm.org/hapijs/lout?type=dev), at least just to avoid that ugly "insecure" badge :/

**Comment by Marsup** [comment]
At some point I'll just remove those badges, they're just drunk.

**Comment by LasaleFamine** [comment]
I agree. They are not really truthful.

**Comment by Marsup** [comment]
Feel free to update whatever's necessary but there's really not much as I won't bump ranges that still work.

**Comment by LasaleFamine** [comment]
I think we are good right now. Maybe we can come back here later. We can close this for now.
