### ISSUE TITLE
Possible formatting error in templates-->route.html

### ISSUE THREAD

**Issue by webbpinner** [hapijs/lout#164]
I just integrated lout within my hapi project and had an issue with the route view.  The CORS section starting on the last line of the auth section.  Looking at the code it appeared that the auth section was using `<p>/<h4>` for the individual rows vs the rest of the template which was using `<dl>`,`<dt><dd>`.  I converted the auth section of the template to use the `<dl>`,`<dt><dd>` and normalized some indentation discrepancies.  That didn't fix the problem but it did make the resulting code more consistent.  What ultimately did fix the problem was adding a `<br/>` just before the closing `{{/if}}` for the auth section.

Thought I'd share in case this was in fact a bug.

Cheers,
-W

Below is my replacement for the existing auth section in the routes template:

```
                <h3 class="auth">Authentication</h3>
                <dl>
                    <dt class="auth-header auth-strategies">Strategies</dt>
                    <dd class="auth-value auth-strategies">{{this.auth.strategies}}</dd>
                    <dt class="auth-header auth-mode">Mode</dt>
                    <dd class="auth-value auth-mode">{{this.auth.mode}}</dd>
                    {{#if this.auth.payload}}
                    <dt class="auth-header auth-payload">Payload</dt>
                    <dd class="auth-value auth-payload">{{this.auth.payload}}</dd>
                    {{/if}}
                </dl>
                    {{#if this.auth.access}}
                <dl>
                    <dt class="auth-header auth-scope">Scopes</dt>
                    <dd>
                        <ul class="auth-access">
                        {{#each this.auth.access}}
                            <li>
                            {{#if this.scope}}
                                {{#if this.scope.required}}
                                <dt> class="auth-header auth-scope">Required</dt>
                                <dd class="auth-value auth-scope">{{this.scope.required}}</dd>
                                {{/if}}
                                {{#if this.scope.selection}}
                                <dt class="auth-header auth-scope">Selection</dt>
                                <dd class="auth-value auth-scope">{{this.scope.selection}}</dd>
                                {{/if}}
                                {{#if this.scope.forbidden}}
                                <dt class="auth-header auth-scope">Forbidden</dt>
                                <dd class="auth-value auth-scope">{{this.scope.forbidden}}</dd>
                                {{/if}}
                            {{/if}}
                            {{#if this.entity}}
                                <dt class="auth-header auth-entity">Entity</dt>
                                <dd class="auth-value auth-entity">{{this.entity}}</dd>
                            {{/if}}
                            </li>
                        {{/each}}
                        </ul>
                    </dd>
                </dl>
                    {{/if}}
                    {{#if this.auth.tos}}
                <dl>
                    <dt class="auth-header auth-tos">Terms of service</dt>
                    <dd class="auth-value auth-tos">{{this.auth.tos}}</dd>
                </dl>
                    {{/if}}
                <br />
                {{/if}}
```

**Comment by Marsup** [comment]
Not sure what you mean. Can you screenshot what's wrong on the demo site (http://lout.herokuapp.com/docs?server=http://lout.herokuapp.com&path=/withcorstrue#GET) ?

**Comment by webbpinner** [comment]
My bad, should have done that in the first place.
Original:
<img width="908" alt="old" src="https://cloud.githubusercontent.com/assets/1568596/23710380/8a00e252-03ea-11e7-95a4-7e369191616d.png">
Modified:
<img width="908" alt="new" src="https://cloud.githubusercontent.com/assets/1568596/23710379/89fd4cf0-03ea-11e7-8d64-667213c935da.png">

**Comment by Marsup** [comment]
Looks better indeed, I'm probably lacking a route test case for auth + CORS. Do you mind taking a stab at a patch ?

**Comment by webbpinner** [comment]
Just created a pull request.  There appears to be some sort of auto-build process that is indicating build errors although they do not cite errors in the route.html file.  Is there anything I need to do to make this pull request compatible with the master branch?

**Comment by Marsup** [comment]
I will, it's been an outstanding issue for a while now, I need to fix it, but I'll have to require latest versions of everything in the process, hope that's ok with you.
