### ISSUE TITLE
default value not displayed if false

### ISSUE THREAD

**Issue by firsttris** [hapijs/lout#168]
hello,
if a default value is false it will not be displayed. Is this the desired behavior?

#### Example:
'deleted': Joi.boolean().default(false)

#### Row in Template
https://github.com/hapijs/lout/blob/master/templates/type.html#L133

#### Possible Solution
```javascript
{{#isDefined this.flags.default}}
     <dt class="default-value">Default value</dt>
     <dd class="default-value">{{json this.flags.default}}</dd>
{{/isDefined}}

// isDefined.js
module.exports = function (a, opts) {
  if (a === undefined || a === null) {
    return opts.inverse(this);
  }

  return opts.fn(this);
};
```
best regards
Tristan

**Comment by Marsup** [comment]
Close but I chose to re-use a helper that was already there, thanks for the bug report and analysis !
