### ISSUE TITLE
custom text ?

### ISSUE THREAD

**Issue by walshe** [hapijs/lout#170]
Hi

is there anyway one can add any custom text desc for a particular endpoint

**Comment by AdriVanHoudt** [comment]
If you add a description property to the route setting it should pull that in https://github.com/hapijs/lout/blob/master/lib/index.js#L207

**Comment by walshe** [comment]
not understanding..

can you be more specific ?

`    server.route({
        path: '/email',
        method: 'POST',
        handler: EmailHandler.action,
        config: EmailHandler.config,
        settings:{
            description: 'test desc',
            notes : 'test notes'
        }
    });`

**Comment by walshe** [comment]
figured it out:

```
    config: {
        validate: {
            headers: headerSchema,
            payload: emailPayloadSchema
        },
        description: 'test desc',
        notes : 'test notes'

    }
```
