### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lout#175]

**Comment by kreig303** [comment]
Forked this repo to take a stab at this... will have some time over the Thanksgiving holiday.

No promises. :)

**Comment by sholladay** [comment]
@kreig303 are you still planning to work on this?

**Comment by venikman** [comment]
I started adding changes but I am confused with multi-connections. Help to figure out with that.
https://github.com/venikman/lout

**Comment by ferrao** [comment]
@venikman there are no multi-connections anymore. Each hapi server instance can only bind to one port. For multiple connections one has to instantiate multiple server instances.

**Comment by henrikdahl** [comment]
Feel free to try my PR already #177 

Everything should fully work but it still lacks test coverage so it needs some more work before merge ✌️

**Comment by Pokom** [comment]
@henrikdahl I installed your PR locally and was able to run it successfully, with relatively minor changes to the example code. As far as the tests, is there anyway I can assist you on this?

**Comment by ferrao** [comment]
Working fine for me.

**Comment by henrikdahl** [comment]
@Pokom Sweet. Sure, most if it needs updating to Hapi 17 but also some of it is redundant (legacy Hapi support) now that the requirement is Hapi 17 and up, so it needs to be removed. I'm not fully aware which parts are there to support older versions ✌️

**Comment by Pokom** [comment]
@henrikdahl To be sure: you're referring to https://github.com/hapijs/lout/pull/177/commits/7b0b78ac26e4a57b69f588efeaf5bbf06fda6051 correct? If so, I can certainly try to update the test suite. If I need some assistance, what's your preferred way of getting in touch?

**Comment by henrikdahl** [comment]
@Pokom It's actually wrong, it needs to be async/await. What about HapiJS Slack channel? ✌️

**Comment by Pokom** [comment]
@henrikdahl I may need an invite, but I promise to be nice 😄

**Comment by henrikdahl** [comment]
@Pokom https://join.slack.com/t/hapihour/shared_invite/enQtMjM5Njk1NDgzNTY5LThmODkxODIzOTg5NjJjODFiYjcxZDMxMTAyMzBkZDk3MWY4MTFlNDAyMTU3MmUwMmM0Y2UwMjU3YjAwYjRkN2E
