### ISSUE TITLE
Warning when install the module

### ISSUE THREAD

**Issue by rokity** [hapijs/lout#181]
Hi

He gives me this warning when I install the package.
`warning " > lout@11.1.0" has incorrect peer dependency "joi@13.x.x"`
How can I fix it?

**Comment by Marsup** [comment]
The answer is in the version of joi you use, and you didn't provide this information.

**Comment by rokity** [comment]
sorry

**Comment by Marsup** [comment]
Do you consider it fixed ? I'm not sure about your answer.

**Comment by rokity** [comment]
I posted it in Joi

**Comment by Marsup** [comment]
OK, then you didn't understand my answer. You're having an incompatibility between your lout and joi version, I'm asking which versions you're using.

**Comment by rokity** [comment]
- node version : 9.3.0
- joi version : 14.0.0
- OS : MacOS Mojave

**Comment by rokity** [comment]
I don't know why I don't have this issue now.
