### ISSUE TITLE
Display sample request/response

### ISSUE THREAD

**Issue by geek** [hapijs/lout#40]
If an endpoint has a payload validation schema then we can generate a sample request payload to display (Instead of adding mock data, it could be { "item": "string", "item2": 100 }

If the endpoint also has response validation then we can also provide a sample response body.

**Comment by seanrucker** [comment]
I see that using .example() I can now provide sample payloads, but what about sample responses?

**Comment by Marsup** [comment]
Same thing ?

**Comment by seanrucker** [comment]
I had sample set to 0 as I don't actually want to validate my API responses, I was just using it for lout. In this case, lout was not generating any response documentation. Changing sample to > 0 fixed the problem.

**Comment by Marsup** [comment]
This might be a problem with hapi then.

**Comment by Marsup** [comment]
I don't think there's anything I can do about that  : https://github.com/hapijs/hapi/blob/d7fd5a8845d9f089978b83a3989d7ece799fc49c/lib/route.js#L108-L112

**Comment by seanrucker** [comment]
No worries, I can work around this. Thanks for looking into it!

**Comment by nickux** [comment]
@Marsup I'm not sure I understand the answer to @seanrucker request for providing sample responses. Are you saying to also use example() for that? If so, I don't see how that works with lout. Can you explain the right way to provide sample responses?

**Comment by Marsup** [comment]
That's right, the only way to do that currently is to use .example(), probably at the top level since it doesn't go down the validation tree to build a sample.
