### ISSUE TITLE
Number min/max is not documented

### ISSUE THREAD

**Issue by igor-galchevsky** [hapijs/lout#98]
**version**

    "lout" : "^6.0.1"

**config**

    server.route({
        method: 'POST', path: '/test',
        config: {
          validate : {
            payload: {
              page : Joi.number().min(1).max(99999).required()
            }
          },
          handler: function(req, resp) {
            resp('test');
          }
        }
    });

**result in /docs**

    page 
    
    Type
    
    number
    Forbidden Values
    Infinity
    -Infinity

No mentioning of .min(1).max(99999)

**Comment by Marsup** [comment]
That's a small mistake. May I ask which Joi version you have ?

**Comment by igor-galchevsky** [comment]
"joi" : "^5.1.0"

**Comment by Marsup** [comment]
Closed by 6203ac3b6a7b9f256747472571b554d9e6a3a746.
